surface.CreateFont( 'font_base', {font = 'Exo 2 Semi Bold',size = 32,weight = 0,underline = false,extended = true,})
surface.CreateFont( 'font_base_big', {font = 'Arial',size = 81,weight = 500,extended = true,})
surface.CreateFont( 'font_base_rotate', {font = 'Tahoma',size = 38,weight = 0,extended = true,})
surface.CreateFont( 'font_base_normal', {font = 'Arial',size = 56,weight = 0,underline = true,extended = true})
surface.CreateFont( 'font_base_24', {font = 'Arial',size = 24,weight = 500,extended = true,})
surface.CreateFont( 'font_base_22', {font = 'Arial',size = 22,weight = 0,extended = true,})
surface.CreateFont( 'font_base_54', {font = 'Arial',size = 38,weight = 0,extended = true,})
surface.CreateFont( 'font_base_18', {font = 'Arial',size = 18,weight = 500,extended = true,})
surface.CreateFont( 'font_base_small', {font = 'Default',size = 14,weight = 300,underline = true,extended = true,})
surface.CreateFont( 'font_base_12', {font = 'Default',size = 12,weight = 0,underline = true,extended = true})
surface.CreateFont( 'font_base_hud', {font = 'Arial',size = 26,weight = 0,underline = true,extended = true})
surface.CreateFont( 'font_base_84_normal', {font = 'Arial',size = 84,weight = 0,underline = true,extended = true})
surface.CreateFont( 'font_base_84', {font = 'Exo 2 Semi Bold',size = 84,weight = 0,underline = true,extended = true})
surface.CreateFont( 'font_base_54', {font = 'Exo 2 Semi Bold',size = 54,weight = 0,underline = true,extended = true})
surface.CreateFont( 'font_base_543', {font = 'Exo 2 Semi Bold',size = 30,weight = 0,underline = true,extended = true})
surface.CreateFont( 'font_base_544', {font = 'Exo 2 Semi Bold',size = 50,weight = 0,underline = true,extended = true})
surface.CreateFont( 'font_base_warning', {font = 'Exo 2 Bold',size = 16,weight = 0,underline = false,extended = true})
surface.CreateFont( 'font_base_close', {font = 'Exo 2 Bold',size = 16,weight = 0,underline = false,extended = true})
surface.CreateFont( 'font_notify', {font = 'Arial',size = 18,weight = 500,extended = true})
surface.CreateFont( 'font_base_45', {font = 'Arial',size = 45,weight = 100, extended = true,})
surface.CreateFont( 'font_roboto_24', { font = 'Roboto', size = 24, weight = 100, extended = true })
surface.CreateFont( 'font_roboto_21', { font = 'Roboto', size = 21, weight = 100, extended = true })

surface.CreateFont( 'font_base_big_s', {font = 'Arial', blursize = 5, size = 81, weight = 500, extended = true})

surface.CreateFont( 'font_base_large', {font = 'Arial',extended = true,size = 100,weight = 500})